/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 24-sept.-2021 6:53:35 a. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tblOpcion_tblPregunta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [tblOpcion] DROP CONSTRAINT [FK_tblOpcion_tblPregunta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tblPregunta_tblCategoria]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [tblPregunta] DROP CONSTRAINT [FK_tblPregunta_tblCategoria]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tblCategoria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tblCategoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tblJugador]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tblJugador]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tblOpcion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tblOpcion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tblPregunta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tblPregunta]
GO

/* Create Tables */

CREATE TABLE [tblCategoria]
(
	[intIdCategoria] int NOT NULL IDENTITY (1, 1),
	[intNivel] int NULL,
	[intPremio] int NULL,
	[blnActivo] bit NULL DEFAULT 1,
	[dtmActualiza] datetime NULL DEFAULT GETDATE()
)
GO

CREATE TABLE [tblJugador]
(
	[intIdJugador] int NOT NULL IDENTITY (1, 1),
	[intPuntaje] int NULL,
	[strNombre] nvarchar(max) NULL,
	[blnActivo] bit NULL DEFAULT 1,
	[dtmActualiza] datetime NULL DEFAULT GETDATE()
)
GO

CREATE TABLE [tblOpcion]
(
	[intIdOpcion] int NOT NULL IDENTITY (1, 1),
	[intIdPregunta] int NULL,
	[strOpcion] nvarchar(max) NULL,
	[blnActivo] bit NULL DEFAULT 1,
	[dtmActualiza] datetime NULL DEFAULT GETDATE()
)
GO

CREATE TABLE [tblPregunta]
(
	[intIdPregunta] int NOT NULL IDENTITY (1, 1),
	[intIdCategoria] int NULL,
	[strPregunta] nvarchar(max) NULL,
	[strRespuesta] nvarchar(max) NULL,
	[blnActivo] bit NULL DEFAULT 1,
	[dtmActualiza] datetime NULL DEFAULT GETDATE()
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [tblCategoria] 
 ADD CONSTRAINT [PK_tblCategoria]
	PRIMARY KEY CLUSTERED ([intIdCategoria] ASC)
GO

ALTER TABLE [tblJugador] 
 ADD CONSTRAINT [PK_tblJugador]
	PRIMARY KEY CLUSTERED ([intIdJugador] ASC)
GO

ALTER TABLE [tblOpcion] 
 ADD CONSTRAINT [PK_tblOpciones]
	PRIMARY KEY CLUSTERED ([intIdOpcion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_tblOpcion_tblPregunta] 
 ON [tblOpcion] ([intIdPregunta] ASC)
GO

ALTER TABLE [tblPregunta] 
 ADD CONSTRAINT [PK_tblPregunta]
	PRIMARY KEY CLUSTERED ([intIdPregunta] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_tblPregunta_tblCategoria] 
 ON [tblPregunta] ([intIdCategoria] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [tblOpcion] ADD CONSTRAINT [FK_tblOpcion_tblPregunta]
	FOREIGN KEY ([intIdPregunta]) REFERENCES [tblPregunta] ([intIdPregunta]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [tblPregunta] ADD CONSTRAINT [FK_tblPregunta_tblCategoria]
	FOREIGN KEY ([intIdCategoria]) REFERENCES [tblCategoria] ([intIdCategoria]) ON DELETE No Action ON UPDATE No Action
GO
